### ISSUE TITLE
Different results using my own training model

### ISSUE THREAD

**Issue by zjcbatman** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#16]
Hi, @ayooshkathuria , recently, I have trained my own model on ImageNet2015 using the C source code from the official site. When I tested my model on the official C code using some images, I got some normal results which means my model has no problem. However, when I tested my model on your code, results were different and bad. I don't know why. I have already changed .cfg file,  .weights file and the class name file. 
This is the result I got using the official C code: 
![image](https://user-images.githubusercontent.com/16145164/40823756-245c73d6-65a4-11e8-9884-fb4670720628.png)
But I would get no car if I run your code using my model.
![image](https://user-images.githubusercontent.com/16145164/40823824-6a1d02c8-65a4-11e8-93b0-e84347ef0976.png)

**Comment by LittleSunH** [comment]
I have some question. I have trained my own model on my own dataset using darknet and got a .weights file. When I want to change it to pytorch using this code,I got this problem:
Traceback (most recent call last):
  File "video.py", line 57, in <module>
    model.load_weights(args.weightsfile)
  File "C:\Users\LittleSunH\Desktop\YOLO_v3_tutorial_from_scratch-master\darknet.py", line 314, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: invalid argument 2: size '[256 x 128 x 3 x 3]' is invalid for input with 264248 elements at ..\aten\src\TH\THStorage.cpp:84

what should I do?

**Comment by matursi** [comment]
I also have the same error as LittleSunH, but with the pre-trained weights: 

File "darknet.py", line 309, in <module>
    model.load_weights('yolov3.weights')
  File "darknet.py", line 293, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: invalid argument 2: size '[512 x 1024 x 1 x 1]' is invalid for input with 471805 elements at /pytorch/aten/src/TH/THStorage.cpp:84

**Comment by juanmed** [comment]
@LittleSunH  @matursi  I think #44 might give you some insights on what is happening. https://github.com/ayooshkathuria/YOLO_v3_tutorial_from_scratch/issues/44
