### ISSUE TITLE
Error doing detection using Tiny_yolo network

### ISSUE THREAD

**Issue by akshayjrkp** [ayooshkathuria/YOLO_v3_tutorial_from_scratch#17]
I get this error:

Traceback (most recent call last):
  File "detect.py", line 171, in <module>
    model(get_test_input(inp_dim, CUDA), CUDA)
  File "/home/akshayj/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/akshayj/pytorch-yolo-v3/darknet.py", line 325, in forward
    x = torch.cat((map1, map2), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 416 and 832 in dimension 2 at /opt/conda/conda-bld/pytorch_1524580978845/work/aten/src/THC/generic/THCTensorMath.cu:111

Any Idea Why this error occurs. Thanks in advance.

**Comment by ayooshkathuria** [comment]
This is a known issue. I'm busy at the moment. Won't be able to look it up until the end of this month. If you solve this, feel free to open a PR.

**Comment by AhmedMagdyHendawy** [comment]
did you solve it?

**Comment by AbanoubMamdouh** [comment]
@ayooshkathuria Any updates on working with the tiny yolov3 model? Problem seems to be in the route layer in the create_modules function
Thanks in advance!

**Comment by AbanoubMamdouh** [comment]
Did some fixes, take a look at it here: https://github.com/AbanoubMamdouh/YOLO_v3_tutorial_from_scratch
